// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiV8qRIOFuvsPbhg52fvyf9XssB7t0M60',
    appId: '1:500315283976:web:b288a0fd0c0b34698fe7bd',
    messagingSenderId: '500315283976',
    projectId: 'devcommunity-d28c1',
    authDomain: 'devcommunity-d28c1.firebaseapp.com',
    storageBucket: 'devcommunity-d28c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw344vG7QZCFoF-OPqs9KK2tOpA6cbgn4',
    appId: '1:500315283976:android:b65a10dc6b9ca5378fe7bd',
    messagingSenderId: '500315283976',
    projectId: 'devcommunity-d28c1',
    storageBucket: 'devcommunity-d28c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcl6ZSu94N9zPpnvKqwT9GEtt5KUviXM',
    appId: '1:500315283976:ios:6996c584e038d7e58fe7bd',
    messagingSenderId: '500315283976',
    projectId: 'devcommunity-d28c1',
    storageBucket: 'devcommunity-d28c1.appspot.com',
    iosClientId: '500315283976-8ji04u61vnf5r12qtptj7c9vj43p8up1.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityDev',
  );
}
