#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/hadeel/Development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/hadeel/Desktop/Flutter Bootcamp/DevCommunity/DevCommunity"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/hadeel/Desktop/Flutter Bootcamp/DevCommunity/DevCommunity/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.0.1"
export "FLUTTER_BUILD_NUMBER=0.0.1"
export "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/hadeel/Desktop/Flutter Bootcamp/DevCommunity/DevCommunity/.dart_tool/package_config.json"
